name: MkDocs Deploy

on:
  push:
    branches: [ master ]
    paths: 
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install mkdocs
        run: |
          sudo apt-get -y install mkdocs
          
      - uses: actions/checkout@v2    
      - name: mkdocs gh-deploy
        run: |
          mkdocs gh-deploy
