name: MkDocs Deploy

on:
  push:
    branches: [ master ]
    paths: 
      - 'docs/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths: 
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - name: Deploy to production
        if: github.ref == 'refs/heads/master'
        run: |
          git config user.name 'github-actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          mkdocs gh-deploy --force
      - name: Deploy preview
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: preview-gh-pages
